version: "3"

services:
  karassistant-back:
    #build: .
    image: codyisthesenate/karassistant-api:0.0.2
    restart: always
    container_name: karassistant-back-${ENV_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .env:/data/Karassistant/.env
      - kara-data:/data/Karassistant/data
      - kara-logs-api:/data/Karassistant/logs
      - kara-versions:/data/Karassistant/versions
    ports:
      - ${PORT_BACK}:3000
    networks:
      - karassistant

networks:
  karassistant:

volumes:
  kara-data:
  kara-logs-api:
  kara-versions:
  kara-data-skills:
  kara-data-vectors:
